if $args[0] = 'atm_str1': $result = '<a href="exec:gs''zz_atm'',''money2card''">Положить деньги на счёт</a><br><a href="exec:gs''zz_atm'',''money_from_card''">Снять деньги со счёта</a><br><a href="exec:gs''zz_atm'',''mobile_payment''">Пополнить баланс мобильного</a><br><a href="exec:gt''zz_atm'',''house_payment''">Аренда жилья онлайн</a><br>'
if $args[0] = 'atm_str2': $result = '<a href="exec:gs''zz_atm'',''internet_payment''">Оплатить интернет</a><br>'
if $args[0] = 'atm_str3': $result = 'Универсальный банковский терминал'
if $args[0] = 'atm_str4': $result = 'Универсальный банковский терминал, где вы можете положить или снять деньги со счета, пополнить баланс мобильного, а также оплатить некоторые услуги.'
if $args[0] = 'atm_str5': $result = 'Сколько денег вы хотите положить на счет?'
if $args[0] = 'atm_str6': $result = '<red>У вас недостаточно денег на счету (сейчас <<karta>>) для проведения данной операции.</red>'
if $args[0] = 'atm_str7': $result = 'Вы положили на счёт <<kartaIN>> рублей, теперь на вашем счету <<karta>> рублей.'
if $args[0] = 'atm_str8': $result = 'Сколько денег вы хотите снять со счета?'
if $args[0] = 'atm_str9': $result = 'Вы сняли со счёта <<kartaOUT>> рублей, теперь на вашем счету <<karta>> рублей.'
if $args[0] = 'atm_str10': $result = 'Вы оплатили <<i>> часов интернета, теперь у вас <<internet>> часов интернета. С вашего счета сняли <<i*10>> рублей. Сейчас на вашем банковском счету <<karta>> рублей.'
if $args[0] = 'atm_str11': $result = 'Сколько часов интернета вы хотите оплатить? (час = 10 руб.)'
if $args[0] = 'atm_str12': $result = 'Вы положили <b><<i>></b> рублей на счет. Сейчас на вашем банковском счету <<karta>> рублей.'
if $args[0] = 'atm_str13': $result = 'Тут можно арендовать квартиру онлайн за 10000 рублей в месяц.'
if $args[0] = 'atm_str14': $result = '<br>У вас <B><<ArendHouseSL>> дней</B> аренды.'
if $args[0] = 'atm_str15': $result = '<br><a href="exec: gt ''zz_atm'', ''house_payment_end'', 1">Аренда квартиры на 1 месяц</a><br><a href="exec: gt ''zz_atm'', ''house_payment_end'', 3">Аренда квартиры на 3 месяца</a><br><a href="exec: gt ''zz_atm'', ''house_payment_end'', 6">Аренда квартиры на 6 месяцев</a>'
if $args[0] = 'atm_str16': $result = 'Вы быстро и легко арендуете квартиру в Южном районе на <<i*30>> дней. Теперь у вас <B><<ArendHouseSL>> дней</B> аренды.'