if $args[0] = 'local_str1': $result = 'Сев на кресло, вы высунули язык, мастер проколол вам язык и вставил туда штангу.'
if $args[0] = 'local_str2': $result = 'Мастер вынул штангу из вашего языка.'
if $args[0] = 'local_str3': $result = 'Мастер проколол вам губу и вставил туда кольцо.'
if $args[0] = 'local_str4': $result = 'Мастер вынул кольцо из вашей губы.'
if $args[0] = 'local_str5': $result = 'Мастер проколол вам уши и вставил туда сережки.'
if $args[0] = 'local_str6': $result = 'Мастер вынул серьги из ваших ушей.'
if $args[0] = 'local_str7': $result = 'Мастер проколол вам нос и вставил туда кольцо.'
if $args[0] = 'local_str8': $result = 'Мастер вынул кольцо из вашего носа.'
if $args[0] = 'local_str9': $result = 'Мастер проколол вам бровь и вставил туда штангу.'
if $args[0] = 'local_str10': $result = 'Мастер вынул штангу из вашей брови.'
if $args[0] = 'local_str11': $result = 'Мастер проколол вам соски и вставил туда колечки.'
if $args[0] = 'local_str12': $result = 'Мастер вынул колечки из ваших сосков.'
if $args[0] = 'local_str13': $result = 'Мастер проколол вам половые губы и вставил туда колечки.'
if $args[0] = 'local_str14': $result = 'Мастер вынул колечки из ваших половых губ.'
if $args[0] = 'local_str15': $result = 'Мастер проколол вам пупок и вставил туда штангу.'
if $args[0] = 'local_str16': $result = 'Мастер вынул штангу из вашего пупка.'
if $args[0] = 'local_str17': $result = 'Мастер проколол вам клитор и вставил туда штангу.'
if $args[0] = 'local_str18': $result = 'Мастер вынул штангу из вашего клитора.'
if $args[0] = 'local_str19': $result = 'Небольшой салон где работает мастер одиночка.'
if $args[0] = 'local_str20': $result = '<a href="exec:dynamic $pirsyaz">'+iif(pirsA=0,'Сделать','Убрать')+' пирсинг языка 2000 рублей</a><br><a href="exec:dynamic $pirsnos">'+iif(pirsD=0,'Сделать','Убрать')+' пирсинг носа 2000 рублей</a><br><a href="exec:dynamic $pirsbro">'+iif(pirsE=0,'Сделать','Убрать')+' пирсинг бровей 5000 рублей</a>'
if $args[0] = 'local_str21': $result = '<a href="exec:dynamic $pirssos">'+iif(pirsF=0,'Сделать','Убрать')+' пирсинг сосков 5000 рублей</a><br><a href="exec:dynamic $pirspyp">'+iif(pirsN=0,'Сделать','Убрать')+' пирсинг пупка 5000 рублей</a>'
if $args[0] = 'local_str22': $result = '<a href="exec:dynamic $pirsvla">'+iif(pirsG=0,'Сделать','Убрать')+' пирсинг половых губ 7000 рублей</a><br><a href="exec:dynamic $pirsclit">'+iif(pirsGL=0,'Сделать','Убрать')+' пирсинг клитора 7000 рублей</a>'