! id_name id_img id_description id_action
! это просто структурированный список возможного инвентаря, а также вся подробная  информация по ним
! все взаимодействие с инвентарем происходит тут в этой переменной $inventory[0+'_'+'count']
! возможно добавление своих оригинальных данных, например $data['0_alco'] = '40 градусов'
! вызов в коде - func('inventory', ИДЕНТИФИКАТОР, 'КЛЮЧ' ), пример func('inventory', 0, 'name') - водка
! Изменить количество на число - $inventory[ИДЕНТИФИКАТОР+'_count'] += 1, пример $inventory[0+'_count'] += 1- увеличит хлеб на 1
$data['0_name'] = 'Хлеб'
$data['0_img'] = 'bread.png'
$data['0_description'] = 'Буханка хлеба'
$data['0_action'] = 'Съесть'
$data['1_name'] = 'Водка'
$data['1_img'] = 'vodka.png'
$data['1_description'] = 'Бутылка водка'
$data['1_action'] = 'Выпить'
$data['2_name'] = 'Сосиски'
$data['2_img'] = 'sausage.png'
$data['2_description'] = 'Толстые длинные сосиски с солоноватым привкусом'
$data['2_action'] = 'Сожрать'
$data['3_name'] = 'Куриные крылышки'
$data['3_img'] = 'fried_chicken.png'
$data['3_description'] = 'Сочные куриные крылышки'
$data['3_action'] = 'Съесть'
$data['4_name'] = 'Шоколад'
$data['4_img'] = 'chocolate.png'
$data['4_description'] = 'Плитка неплохого шоколада'
$data['4_action'] = 'Съесть'
$data['5_name'] = 'Бутылочка воды'
$data['5_img'] = 'water_bottle.png'
$data['5_description'] = 'Кристалльно чистая вода из артезианской скважины'
$data['5_action'] = 'Выпить'
$data['6_name'] = 'Бутерброд'
$data['6_img'] = 'sandwich.png'
$data['6_description'] = 'Обычный сендвич'
$data['6_action'] = 'Перекусить'
$data['7_name'] = 'Печенье'
$data['7_img'] = 'cookie.png'
$data['7_description'] = 'Сладкое шоколадное печенье'
$data['7_action'] = 'Перекусить'
$data['8_name'] = 'Вино'
$data['8_img'] = 'wine.png'
$data['8_description'] = 'Бутылка дешевого вина'
$data['8_action'] = 'Выпить'
$data['9_name'] = 'TicTac'
$data['9_img'] = 'tictac.png'
$data['9_description'] = 'Сладкие драже, освежающие дыхание. И всего 2 калории!'
$data['9_action'] = 'Съесть'
$result = $data[args[0]+'_'+$args[1]]
killvar '$data'