gs 'zz_render','Testroom'
act '<b>Back</b>': gt 'bedrPar'
'<br><br><a href="exec: gt ''zz_achievements'',''ach_page''">zz_achievements</a>'
'<a href="exec: $control_point = ''gorodok'' & gt ''zz_park''">zz_park test</a>'
'<a href="exec: gt ''skk_events'',''karate_init''">karate_init test</a>'
'<a href="exec: $npc[''0,karate_count''] = 30 & $npc[''0,karate''] = 1 & Jab = 100 & Punch = 100 & Kik = 100 & KikDef = 100 & gt ''skk_events'',''karate_training''">karate: boxing > 80 test</a>'
'<a href="exec: gt ''mey_katya_events'',''drunk_meet''">katya drunk_meet</a>'
'<a href="exec: $npc[''14,qwKatya''] = 2 & lesbian = 1 & gt ''mey_katya_events'',''sleep_together'' ">katya sleep_together (touch=0)</a>'
'<a href="exec: $npc[''14,qwKatya''] = 4 & lesbian = 1 & gt ''mey_katya_events'',''sleep_together'' ">katya sleep_together (touch=1)</a>'
'<a href="exec: $npc[''14,qwKatya''] = 6 & lesbian = 1 & gt ''mey_katya_events'',''sleep_together'' ">katya sleep_together (touch=2)</a>'
'<a href="exec: gs ''mey_katya_events'',''park_walk''">mey_katya_events park_walk</a>'
'<a href="exec: gs ''mey_katya_events'',''bath_sex''">mey_katya_events bath_sex</a>'
'<a href="exec: gs ''mey_home'',5">mey_home katya_room test</a>'
'<a href="exec: $npc[''14,qwKatya''] = 40 & gs ''mey_katya_events'',''room_sex''">mey_katya_events room_sex stage=40</a>'
'<a href="exec: $npc[''14,qwKatya''] = 43 & gs ''mey_katya_events'',''room_sex''">mey_katya_events room_sex stage=43</a>'
'<a href="exec: $npc[''14,qwKatya''] = 45 & gs ''mey_katya_events'',''room_sex''">mey_katya_events room_sex stage=45</a>'
'<a href="exec: $npc[''14,qwKatya''] = 50 & gs ''mey_katya_events'',''room_sex''">mey_katya_events room_sex stage=50</a>'
'<a href="exec: $npc[''14,qwKatya''] = 55 & gs ''mey_katya_events'',''disco_observing''">mey_katya_events disco_observing</a>'
'<a href="exec: gt ''mey_katya_events'',''school_no_panty''">mey_katya_events school_no_panty</a>'
'<a href="exec: gt ''mey_katya_events'',''park_sex_prepeare''">mey_katya_events park_sex_prepeare</a>'
'<a href="exec: $npc[''23,qwMain''] = 30 & gs ''npc_editor'',''get_npc_small_profile'',23 & gs ''npc_events_tips'',''init'',23">Note test (Albina)</a>'
'<a href="exec: hour=18 & $npc[''45,know''] = 0 & $npc[''14,qwKatya''] = 10 & gt''mey_home'',-1">mey_tamara_events</a>'
'<a href="exec: shameless[''flag''] = 1 & mastr=1 & gt''mey_katya_events'',''talk_about_sex''">talk_about_sex</a>'
!'<a href="exec:$npc[''14,qwKatya''] = 10 & month = 9 & day = 1 & week = 1 & hour = 15 & gs ''zz_school'',''vacation_status'' & gt ''gorodok''">katya test</a>'
'<a href="exec:gt ''npc_editor'',''get_npc_list''">get_npc_list</a>'
'<a href="exec: gt''sonya'',''falling_drink''">sonya falling_drink</a>'
'<a href="exec:gt ''sonya'',''help_in_park''">sonya help_in_park</a>'
'<a href="exec:gt ''sonya'',''meet_in_dk''">sonya meet_in_dk</a>'
'<a href="exec:gt ''sonya'',''meet_near_school''">sonya meet_near_school</a>'
'<a href="exec:gt ''mey_vika_events'',''random_sex_prepeare''">Рандом с Викой</a>'
'<a href="exec:gt ''mey_katya_events'',''ask_about_trio''">mey_katya_events ask_about_trio</a>'
'<a href="exec:$npc[''26,qwMain'']=21 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, доп.занятие 1</a>'
'<a href="exec:$npc[''26,qwMain'']=22 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, доп.занятие 2</a>'
'<a href="exec:$npc[''26,qwMain'']=23 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, доп.занятие 3</a>'
'<a href="exec:$npc[''26,qwMain'']=24 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, первый секс на доп.занятии</a>'
'<a href="exec:$npc[''26,qwMain'']=26 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, рандомный секс на доп.занятии</a>'
'<a href="exec:gt ''tsarev_events'',''school_breaktime_sex''">Царев, секс на перемене</a>'
'<a href="exec:gt ''tsarev_events'',''school_anal_sex''">Царев, анальный секс после уроков</a>'
'<a href="exec:gt ''tsarev_events'',''home_first_sex''">Царев, первый домашний секс</a>'
'<a href="exec:gt ''tsarev_events'',''home_second_sex''">Царев, второй домашний секс</a>'
'<a href="exec:$npc[''26,qwMain'']=30&gt ''gorodok''">Царев, дом, тест</a>'
'<a href="exec:gt ''tsarev_events'',''teacher_goto_home''">ГГ пытается попасть во двор учителя</a>'
'<a href="exec:gt ''tsarev_events'',''teacher_yard''">ГГ попала во двор учителяя</a>'
'<a href="exec:gt ''tsarev_events'',''teacher_fuckoff''">ГГ послала учителя</a>'
'<a href="exec:gt ''tsarev_events'',''teacher_complain''">ГГ жалеется учителю</a>'
'<a href="exec:gt ''tsarev_events'',''teacher_sex''">Секс с учителем дома после подвала</a>'
'<a href="exec:gt ''tsarev_events'',''stealing_keys_init''">Воровство ключей у Леры</a>'
'<a href="exec:gt ''hotel'',''maid_event'', 0">Горничная в отеле</a>'
'<a href="exec:gt ''hotel'',''maid_event_1'', 0">Горничная в отеле 1</a>'
'<a href="exec:gt ''hotel'',''maid_event_2'', 0">Горничная в отеле 2</a>'
'<a href="exec:gt ''hotel'',''maid_event_3''">Горничная в отеле 3</a>'
'<a href="exec:gt ''hotel'',''maid_event_4'', 0">Горничная в отеле 4</a>'
'<a href="exec:gt ''hotel'',''maid_event_5'', 0">Горничная в отеле 5</a>'
'<a href="exec:gt ''hotel'',''maid_event_6'', 0">Горничная в отеле 6</a>'
'<a href="exec:gt ''hotel'',''maid_event_7'', 0">Горничная в отеле 7</a>'
'<a href="exec:gt ''hotel'',''maid_event_worker_1'', 0">Горничная в отеле рабочий 1</a>'
'<a href="exec:gt ''hotel'',''maid_event_worker_2'', 0">Горничная в отеле рабочий 2</a>'
'<a href="exec:gt ''sisterQW'',''incest_event1'',0 ">инцест ивент 1</a>'
'<a href="exec:gt ''sisterQW'',''incest_event2'',0 ">инцест ивент 2</a>'
'<a href="exec:gt ''sisterQW'',''incest_event3'',0 ">инцест ивент 3</a>'
'<a href="exec:gt ''sisterQW'',''incest_event3_sub'',0 ">инцест ивент 3 саб</a>'
'<a href="exec:gt ''sisterQW'',''incest_event4'',0 ">инцест ивент 4</a>'
'<a href="exec:gt ''sisterQW'',''incest_event5'',0 ">инцест ивент 5</a>'
'<a href="exec:gt ''sisterQW'',''incest_event5sub'',0 ">инцест ивент 5 саб</a>'
'<a href="exec:gt ''sisterQW'',''incest_event6'',0 ">инцест ивент 6</a>'
'<a href="exec:gt ''sisterQW'',''incest_event6shop'',0 ">инцест ивент 6 шоп</a>'
'<a href="exec:gt ''sisterQW'',''incest_event6sub'',0 ">инцест ивент 6 саб</a>'
'<a href="exec:gt ''sisterQW'',''incest_event7'',0 ">инцест ивент 7</a>'
'<a href="exec:gt ''sisterQW'',''incest_event8'',0 ">инцест ивент 8</a>'
'<a href="exec:gt ''sisterQW'',''incest_event9'',0 ">инцест ивент 9</a>'
'<a href="exec:gt ''sisterQW'',''incest_event10'',0 ">инцест ивент 10</a>'
'<a href="exec:gt ''sisterQW'',''incest_event10sub'',0 ">инцест ивент 10 саб</a>'
'<a href="exec:gt ''sisterQW'',''incest_event11'',0 ">инцест ивент 11</a>'
'<a href="exec:gt ''sisterQW'',''incest_mini1'',0 ">инцест ивент мини 1</a>'
'<a href="exec:gt ''sisterQW'',''incest_mini2'',0 ">инцест ивент мини 2</a>'
'<a href="exec:gt ''sisterQW'',''incest_dialog1'',0 ">инцест ивент диалог 1</a>'
'<a href="exec:gt ''sisterQW'',''incest_dialog2'',0 ">инцест ивент диалог 2</a>'
'<a href="exec:gt ''sisterQW'',''incest_dialog3'',0 ">инцест ивент диалог 3</a>'
'<a href="exec:gt ''front_door_event'',''cherdak_ev1''">Ивент на чердаке</a>'
'<a href="exec:gt ''front_door_event'',''front_ev1_init''">Ивент у подъезда</a>'
'<a href="exec:gt ''front_door_event'',''front_ev2''">Ивент в подъезде</a>'
act 'Универ': gt 'Testroom','university'
if $ARGS[0] = 'university':
	*clr& cla
	school['certificate'] = 1
	'<b>Читы</b>'
	'Это чит. В основную игру не пойдёт ибо нех)) Сейчас уровень знаний <<university[''progress'']>>. Остальные характеристики можно в стандартном чит-меню подогнать.'
	'<a href="exec:university[''progress''] += 5 & gt''Testroom'',''university''">Повысить уровень знаний в универе на 5 едениц</a>.'
	'<a href="exec:university[''progress''] += 10 & gt''Testroom'',''university''">Повысить уровень знаний в универе на 10 едениц</a>.'
	'<a href="exec:university[''progress''] += 25 & gt''Testroom'',''university''">Повысить уровень знаний в универе на 25 едениц</a>.'
	'<a href="exec:university[''course_work''] = 100 & gt''Testroom'',''university''">Готовый курсовик</a>.'
	'<a href="exec:university[''graduate_work''] = 100 & gt''Testroom'',''university''">Готовая дипломная работа</a>.'
	'<b>Основные действия</b>'
	'<a href="exec:gt''university_events'',''preparatory_classes''">Подготовительные курсы</a>. Повышают интеллект на 1 еденицу за пять занятий.'
	'<a href="exec:gt''university_events'',''entrance_exam''">Вступительные экзамены</a>. Расчитываются по формуле интеллект + успеваемость в школе + внешность/10 - опьянение*10'
	'<a href="exec:gt''university_events'',''lecture''">Лекции</a>. Тут многое влияет на конечный результ - возбуждение, опъянение, сонливость, настроение.'
	'<a href="exec:university[''vacation''] = 2 & gt''university_events'',''exam''">Экзамены - Зимняя сессия 1 курс</a>.'
	'<a href="exec:university[''vacation''] = 3 & gt''university_events'',''exam''">Экзамены - Летняя сессия 1 курс</a>.'
	'<a href="exec:university[''vacation''] = 5 & gt''university_events'',''exam''">Экзамены - Зимняя сессия 2 курс</a>.'
	'<a href="exec:university[''vacation''] = 6 & gt''university_events'',''exam''">Экзамены - Летняя сессия 2 курс</a>.'
	if university['course_work'] >= 100:'<a href="exec:gt''university_events'',''exam''">Сдать курсовик</a>.'
	if university['graduate_work'] >= 100:'<a href="exec: gt''university_events'',''exam''">Защитить диплом</a>.'
	'<b>Локации</b>'
	'<a href="exec:gt''university'',''start''">Холл универа</a>.'
	'<a href="exec:gt''university'',''accounting''">Бухгалтерия</a>.'
	'<a href="exec:gt''university'',''deanery''">Деканат</a>.'
	'<a href="exec:gt''university'',''toilet''">Туалет</a>. При возбуждении можно мастурбировать в кабинке.'
	'<a href="exec:university[''student''] = 2 & gt''university'',''library''">Библиотека</a>. Только для студентов.'
	act 'Назад': gt 'Testroom'
end