$_vstr['act1'] = 'Your room'
$_vstr['act2'] = 'Leave the room'
$_vstr['act3'] = 'Wardrobe'
$_vstr['act4'] = 'Bed'
$_vstr['act5'] = 'Bookshelf'
$_vstr['act6'] = 'Masturbate'
$_vstr['act7'] = 'Take playing cards'
$_vstr['act8'] = 'Write a term paper'
$_vstr['act9'] = 'Write a thesis paper'
$_vstr['act10'] = 'Notebook'
$_vstr['1'] = 'Small room, where you can find a <a href="exec:GT ''loker'',''start''">wardrobe</a>, your <a href="exec: gs ''bed'',''start''">bed</a>, bed of your sister, writing desk and <a href="exec:gt ''zz_books'',''main''">bookshelf</a>.'
$_vstr['2'] = 'You can see your <a href="exec: GT ''Komp'',''start''">notebook</a>.'
$_vstr['3'] = 'You are ill, so you do not want to practice.'
$_vstr['4'] = 'You have a porn magazine hidden under the mattress.'
$_vstr['5'] = 'You keep <<tovarL>> small items. Maximum you can store in your room 30 pieces of goods.'
$result = $_vstr[$args[0]]
killvar '$_vstr'