$_vstr['act1'] = 'Parents beedroom'
$_vstr['act2'] = 'Watch'
$_vstr['act3'] = 'Leave'
$_vstr['act4'] = 'Steal condoms'
$_vstr['act5'] = 'Leave the room'
$_vstr['act6'] = 'Masturbate'
$_vstr['act7'] = 'Search something'
$_vstr['act8'] = 'Leave'
$_vstr['act9'] = 'Close the wardrobe'
$_vstr['act10'] = 'Leave'
$_vstr['act11'] = 'Close the door'
$_vstr['act12'] = 'Play with yourself'
$_vstr['act13'] = 'Close'
$_vstr['1'] = 'Mother and stepfather are sleeping on the bed.'
$_vstr['2'] = 'Your mother sleeps on the bed.'
$_vstr['3'] = 'The room in which the parents live. In the center there is a double bed and '+iif((hour>8 and hour<16) or (family_trip_month ! month and week >= 6),'<a href="exec: gt ''bedrPar2'',''parents_wardrobe''"> large wardrobe </a>', 'large wardrobe') + ' near the wall.'
$_vstr['4'] = 'There is a <a href="exec: gt''bedrPar2'',''kamasutra''"> book </a> on the bed.'
$_vstr['5'] = 'You unnoticeable get a few condoms out of the parent^s cache. Now you have <<condom>> condoms.'
$_vstr['6'] = 'You recently took condoms from the parent^s cache. If they are carried too much about it then parents can suspect something.'
$_vstr['7'] = 'On the cover of the book is written "Kamasutra"'
$_vstr['8'] = 'It^s time to get out, or you will be caught by parents ...'
$_vstr['9'] = iif(kamasutra_page < 1,'','<a href="exec: kamasutra_page-=1 & gt''bedrPar2'',''read_book''"> Previous page </a>')+ '	' +iif(kamasutra_page > 45,'','<a href="exec: kamasutra_page+=1 & gt''bedrPar2'',''read_book''"> Next Page </a>')
$_vstr['10'] ='Old soviet cabinet.'
$_vstr['11'] ='You can^t find anything interesting.'
$_vstr['12'] ='There are just clothes and underwear.'
$_vstr['13'] ='You rummaged in the closet, but you found nothing except some underwear'
$_vstr['14'] ='Digging into the closet, you suddenly found a small <a href="exec: gt''bedrPar2'',''momtoy_play''"> dildo </a>'
$_vstr['15'] ='In the box with the mother^s underwear, there is a small <a href="exec: gt ''bedrPar2'',''momtoy_play''"> dildo </a> hidden under the bra and underpants. **"Wow!" you think to yourself. "Let^s remember!"'
$_vstr['16'] ='You have found your mother^s <a href="exec: gt''bedrPar2'',''momtoy_play''"> toy </a> '
$_vstr['17'] ='Walking near the parents^ room, you suddenly hear strange sounds from there.'
$_vstr['18'] ='Of course you can guess what can happen outside the door - you^re an adult girl, but you were embarrassed by the fact that the stepfather usually on Mondays at the warehouse in the city, and returns to home  usually by midnight.'
$_vstr['19'] ='Having succumbed to the temptation of curiosity, you decided to see what happens behind the door. '
$_vstr['20'] ='Having crept up on tiptoe, you gently turned the doorknob and opened the door.'
$_vstr['21'] =', and freeze from what you saw: your mother, lying completely naked on the bed, furiously moving a dildo inside of herself, close her eyes from pleasure and softly moaning.'
$_vstr['22'] ='. "Daddy out of home - my mother going out from her mind" - you ironically sneer at yourself, watching your mother furiously and violently using silicone "man^s substitute", gasping and panting.'
$result = $_vstr[$args[0]]
killvar '$_vstr'