act '<b>Back</b>': gt 'bedrPar'
act 'Cloth Checker': gt 'Testroom','cloth_checker'
!--
	if $args[0] = 'cloth_checker':
		cla
		act 'Back': gt 'Testroom'
		act 'Раздеться': gs 'zz_clothing2','redress',0 & gt 'Testroom','cloth_checker'
		act 'Полотенце': gs 'zz_clothing2','redress',1 & gt 'Testroom','cloth_checker'
		act 'Купальник': gs 'zz_clothing2','redress',2 & gt 'Testroom','cloth_checker'
		act 'Сарафан': gs 'zz_clothing2','redress',3 & gt 'Testroom','cloth_checker'
		act 'Форма': gs 'zz_clothing2','redress',4 & gt 'Testroom','cloth_checker'
		act iif(cloth[1]=1,'Снять','Надеть') + ' трусики':
			cloth[1] = iif(cloth[1] = 1,0,1)
			gt 'Testroom','cloth_checker'
		end
		act iif(cloth[2]=1,'Снять','Надеть') + ' чулки':
			cloth[2] = iif(cloth[2] = 1,0,1)
			gt 'Testroom','cloth_checker'
		end
		*pl 'Одежда: ' + cloth[0]
		*pl 'Трусики: ' + cloth[1]
		*pl 'Чулки: ' + cloth[2]
		*pl 'Одежда (пр): ' + cloth[3]
		*pl 'Трусики (пр): ' + cloth[4]
		*pl 'Чулки (пр): ' + cloth[5]
		*pl '<hr>'
		exit
	end
gs 'zz_render','','','****<a href="exec: gt ''zz_cafe'',''work''">zz_cafe work</a>'
gs 'zz_render','','','<a href="exec: gt ''zz_clothing2'',''list''">zz_clothing list</a>'
gs 'zz_render','','','<a href="exec: gt ''zz_clothing2'',''make_shop'',2">zz_clothing shop</a>'
!--
gs 'zz_render','','','<a href="exec: gt ''tanya_events'',''tanya_call_check''">tanya_call_check</a>'
gs 'zz_render','','','<a href="exec: gt ''tanya_events'',''tanya_candle''">tanya_candle</a>'
!--
gs 'zz_render','','','<a href="exec: gt ''mey_tamara_events'',''next_meet''">mey_tamara_events next_meet</a>'
!--
gs 'zz_render','','','<a href="exec: sex = 200 & gs''stat'' & gt ''npc_demarkus'',''park_init''">npc_demarkus park_init</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_demarkus'',''toilet_fuck_vag''">npc_demarkus toilet_fuck_vag</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_demarkus'',''toilet_fuck_anal''">npc_demarkus toilet_fuck_anal</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_demarkus'',''dorm_room''">npc_demarkus dorm_room</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_demarkus'',''visit''">npc_demarkus visit</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_demarkus'',''visit_sex''">npc_demarkus visit_sex</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_demarkus'',''visit_bj''">npc_demarkus visit_bj</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_demarkus'',''visit_anal''">npc_demarkus visit_anal</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_niger'',''park_group_init''">npc_niger park_group_init</a>'
!--
gs 'zz_render','','','<a href="exec: gt ''zz_achievements'',''ach_page''">zz_achievements</a>'
gs 'zz_render','','','<a href="exec: $control_point = ''gorodok'' & gt ''zz_park''">zz_park test</a>'
gs 'zz_render','','','<a href="exec: gt ''skk_events'',''karate_init''">karate_init test</a>'
gs 'zz_render','','','<a href="exec: $npc[''0,karate_count''] = 30 & $npc[''0,karate''] = 1 & Jab = 100 & Punch = 100 & Kik = 100 & KikDef = 100 & gt ''skk_events'',''karate_training''">karate: boxing > 80 test</a>'
gs 'zz_render','','','<a href="exec: gt ''mey_katya_events'',''drunk_meet''">katya drunk_meet</a>'
gs 'zz_render','','','<a href="exec: $npc[''14,qwKatya''] = 2 & lesbian = 1 & gt ''mey_katya_events'',''sleep_together'' ">katya sleep_together (touch=0)</a>'
gs 'zz_render','','','<a href="exec: $npc[''14,qwKatya''] = 4 & lesbian = 1 & gt ''mey_katya_events'',''sleep_together'' ">katya sleep_together (touch=1)</a>'
gs 'zz_render','','','<a href="exec: $npc[''14,qwKatya''] = 6 & lesbian = 1 & gt ''mey_katya_events'',''sleep_together'' ">katya sleep_together (touch=2)</a>'
gs 'zz_render','','','<a href="exec: gs ''mey_katya_events'',''park_walk''">mey_katya_events park_walk</a>'
gs 'zz_render','','','<a href="exec: gs ''mey_katya_events'',''bath_sex''">mey_katya_events bath_sex</a>'
gs 'zz_render','','','<a href="exec: gs ''mey_home'',5">mey_home katya_room test</a>'
gs 'zz_render','','','<a href="exec: $npc[''14,qwKatya''] = 40 & gs ''mey_katya_events'',''room_sex''">mey_katya_events room_sex stage=40</a>'
gs 'zz_render','','','<a href="exec: $npc[''14,qwKatya''] = 43 & gs ''mey_katya_events'',''room_sex''">mey_katya_events room_sex stage=43</a>'
gs 'zz_render','','','<a href="exec: $npc[''14,qwKatya''] = 45 & gs ''mey_katya_events'',''room_sex''">mey_katya_events room_sex stage=45</a>'
gs 'zz_render','','','<a href="exec: $npc[''14,qwKatya''] = 50 & gs ''mey_katya_events'',''room_sex''">mey_katya_events room_sex stage=50</a>'
gs 'zz_render','','','<a href="exec: $npc[''14,qwKatya''] = 55 & gs ''mey_katya_events'',''disco_observing''">mey_katya_events disco_observing</a>'
gs 'zz_render','','','<a href="exec: gt ''mey_katya_events'',''school_no_panty''">mey_katya_events school_no_panty</a>'
gs 'zz_render','','','<a href="exec: gt ''mey_katya_events'',''park_sex_prepeare''">mey_katya_events park_sex_prepeare</a>'
gs 'zz_render','','','<a href="exec: $npc[''23,qwMain''] = 30 & gs ''npc_editor'',''get_npc_small_profile'',23 & gs ''npc_events_tips'',''init'',23">Note test (Albina)</a>'
gs 'zz_render','','','<a href="exec: hour=18 & $npc[''45,know''] = 0 & $npc[''14,qwKatya''] = 10 & gt''mey_home'',-1">mey_tamara_events</a>'
gs 'zz_render','','','<a href="exec: shameless[''flag''] = 1 & mastr=1 & gt''mey_katya_events'',''talk_about_sex''">talk_about_sex</a>'
!'<a href="exec:$npc[''14,qwKatya''] = 10 & month = 9 & day = 1 & week = 1 & hour = 15 & gs ''zz_school'',''vacation_status'' & gt ''gorodok''">katya test</a>'
gs 'zz_render','','','<a href="exec:gt ''npc_editor'',''get_npc_list''">get_npc_list</a>'
gs 'zz_render','','','<a href="exec: gt''sonya'',''falling_drink''">sonya falling_drink</a>'
gs 'zz_render','','','<a href="exec:gt ''sonya'',''help_in_park''">sonya help_in_park</a>'
gs 'zz_render','','','<a href="exec:gt ''sonya'',''meet_in_dk''">sonya meet_in_dk</a>'
gs 'zz_render','','','<a href="exec:gt ''sonya'',''meet_near_school''">sonya meet_near_school</a>'
gs 'zz_render','','','<a href="exec:gt ''mey_vika_events'',''random_sex_prepeare''">Рандом с Викой</a>'
gs 'zz_render','','','<a href="exec:gt ''mey_katya_events'',''ask_about_trio''">mey_katya_events ask_about_trio</a>'
gs 'zz_render','','','<a href="exec:$npc[''26,qwMain'']=21 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, доп.занятие 1</a>'
gs 'zz_render','','','<a href="exec:$npc[''26,qwMain'']=22 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, доп.занятие 2</a>'
gs 'zz_render','','','<a href="exec:$npc[''26,qwMain'']=23 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, доп.занятие 3</a>'
gs 'zz_render','','','<a href="exec:$npc[''26,qwMain'']=24 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, первый секс на доп.занятии</a>'
gs 'zz_render','','','<a href="exec:$npc[''26,qwMain'']=26 & gt ''tsarev_events'',''goto_tsarev_office''">Царев, рандомный секс на доп.занятии</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''school_breaktime_sex''">Царев, секс на перемене</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''school_anal_sex''">Царев, анальный секс после уроков</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''home_first_sex''">Царев, первый домашний секс</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''home_second_sex''">Царев, второй домашний секс</a>'
gs 'zz_render','','','<a href="exec:$npc[''26,qwMain'']=30&gt ''gorodok''">Царев, дом, тест</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_goto_home''">ГГ пытается попасть во двор учителя</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_yard''">ГГ попала во двор учителяя</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_fuckoff''">ГГ послала учителя</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_complain''">ГГ жалеется учителю</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_sex''">Секс с учителем дома после подвала</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''stealing_keys_init''">Воровство ключей у Леры</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_choice_detective1''">tsarev_events teacher_choice_detective1</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_choice_detective2''">tsarev_events teacher_choice_detective2</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_choice_detective3''">tsarev_events teacher_choice_detective3</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_choice_detective4''">tsarev_events teacher_choice_detective4</a>'
gs 'zz_render','','','<a href="exec:gt ''tsarev_events'',''teacher_choice_detective5''">tsarev_events teacher_choice_detective5</a>'
!----------------
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event'', 0">Горничная в отеле</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_1'', 0">Горничная в отеле 1</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_2'', 0">Горничная в отеле 2</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_3''">Горничная в отеле 3</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_4'', 0">Горничная в отеле 4</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_5'', 0">Горничная в отеле 5</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_6'', 0">Горничная в отеле 6</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_7'', 0">Горничная в отеле 7</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_worker_1'', 0">Горничная в отеле рабочий 1</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_event_worker_2'', 0">Горничная в отеле рабочий 2</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_1'', 0">Горничная в отеле администрация скрытая проституция 1</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_reinstatement'', 0">Горничная в отеле восстановление скрытая проституция</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_2'', 0">Горничная в отеле подработка предложение скрытая проституция 2</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_2_next_day'', 0">Горничная в отеле подработка следующий день скрытая проституция 2</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_ask_prostitute_job_loop''">Горничная в отеле скрытая проституция спросить про "работу"</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_3'', 0">Горничная в отеле скрытая проституция 3</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_4'', 0">Горничная в отеле скрытая проституция 4</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_5'', 0">Горничная в отеле скрытая проституция 5</a>'
gs 'zz_render','','','<a href="exec:gt ''hotel'',''maid_admin_6'', 0">Горничная в отеле скрытая проституция 6(баня)</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event1'',0 ">инцест ивент 1</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event2'',0 ">инцест ивент 2</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event3'',0 ">инцест ивент 3</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event3_sub'',0 ">инцест ивент 3 саб</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event4'',0 ">инцест ивент 4</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event5'',0 ">инцест ивент 5</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event5sub'',0 ">инцест ивент 5 саб</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event6'',0 ">инцест ивент 6</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event6shop'',0 ">инцест ивент 6 шоп</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event6sub'',0 ">инцест ивент 6 саб</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event7'',0 ">инцест ивент 7</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event8'',0 ">инцест ивент 8</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event9'',0 ">инцест ивент 9</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event10'',0 ">инцест ивент 10</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event10sub'',0 ">инцест ивент 10 саб</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_event11'',0 ">инцест ивент 11</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_mini1'',0 ">инцест ивент мини 1</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_mini2'',0 ">инцест ивент мини 2</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_dialog1'',0 ">инцест ивент диалог 1</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_dialog2'',0 ">инцест ивент диалог 2</a>'
gs 'zz_render','','','<a href="exec:gt ''sisterQW'',''incest_dialog3'',0 ">инцест ивент диалог 3</a>'
gs 'zz_render','','','<a href="exec:gt ''front_door_event'',''cherdak_ev1''">Ивент на чердаке</a>'
gs 'zz_render','','','<a href="exec:gt ''front_door_event'',''front_ev1_init''">Ивент у подъезда</a>'
gs 'zz_render','','','<a href="exec:gt ''front_door_event'',''front_ev2''">Ивент в подъезде</a>'
! Альгуль
gs 'zz_render','','','<a href="exec:gt ''npc_algul'',''algyl_ev1''">Альгуль, знакомство</a>'
gs 'zz_render','','','<a href="exec:gt ''npc_algul'',''algyl_ev2''">Альгуль, фотосессия</a>'
gs 'zz_render','','','<a href="exec:gt ''npc_algul'',''algyl_ev3''">Альгуль, ивент 3, полизушки</a>'
gs 'zz_render','','','<a href="exec:gt ''npc_algul'',''algyl_ev4''">Альгуль, ивент 4, в душе</a>'
gs 'zz_render','','','<a href="exec:gt ''npc_algul'',''algyl_ev5''">Подглядывание за Айгуль и арабом</a>'
gs 'zz_render','','','<a href="exec:gt ''npc_algul'',''algyl_ev6''">Подглядывание за Айгуль и парнями</a>'
gs 'zz_render','','','<a href="exec: sex = 3000 & anal = 15 & vaginal = 15 & gt ''npc_algul'',''algyl_ev7''">Секс с Айгуль и Олегом</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_algul'',''algyl_ev8''">Секс с Айгуль и парнями</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_algul'',''algyl_ev9''">Светка и Айгуль идут на порнофотосессию к Демаркусу</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_algul'',''algyl_ev10''">Светка подсматривает за групповушкой негров и Айгуль</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_algul'',''algyl_ev11''">Светка и Айгуль трахаються с нигрой</a>'
gs 'zz_render','','','<a href="exec: gt ''npc_algul'',''algyl_ev12''">Завершающий ивент с Айгуль</a>'
!--
gs 'zz_render','','','<a href="exec: hour = 12 & minut = 0 & school[''absent''] = 25 & gt ''zz_school''">Прогулы: начальный даилог</a>'
gs 'zz_render','','','<a href="exec: hour = 15 & minut = 0 & absent[''stage''] = 4 & school[''absent''] = 25 & gt ''gpoli''">Прогулы: визит к доктору</a>'
gs 'zz_render','','','<a href="exec: hour = 15 & minut = 0 & absent[''stage''] = 5 & school[''absent''] = 25 & gt ''zz_school''">Прогулы: отработка у директора</a>'
!--
gs 'zz_render','','','<a href="exec: day = 2 & daystart = 30 & gt ''zz_pornstudio''">Порностудия</a>'
!--
gs 'zz_render','','','<a href="exec: gt ''apartment_south_event'',''thief''">Ограбление квартиры ГГ</a>'
!--
gs 'zz_render','','','<a href="exec: gt ''banda_events'',''banda_event''">Banda0</a>'
gs 'zz_render','','','<a href="exec: gt ''banda_events'',''banda_event1''">Banda1</a>'
act 'Универ': gt 'Testroom','university'
if $ARGS[0] = 'university':
	*clr& cla
	school['certificate'] = 1
	gs 'zz_render','','','<b>Читы</b>'
	gs 'zz_render','','','Это чит. В основную игру не пойдёт ибо нех)) Сейчас уровень знаний <<university[''progress'']>>. Остальные характеристики можно в стандартном чит-меню подогнать.'
	gs 'zz_render','','','<a href="exec:university[''progress''] += 5 & gt''Testroom'',''university''">Повысить уровень знаний в универе на 5 единиц</a>.'
	gs 'zz_render','','','<a href="exec:university[''progress''] += 10 & gt''Testroom'',''university''">Повысить уровень знаний в универе на 10 единиц</a>.'
	gs 'zz_render','','','<a href="exec:university[''progress''] += 25 & gt''Testroom'',''university''">Повысить уровень знаний в универе на 25 единиц</a>.'
	gs 'zz_render','','','<a href="exec:university[''course_work''] = 100 & gt''Testroom'',''university''">Готовый курсовик</a>.'
	gs 'zz_render','','','<a href="exec:university[''graduate_work''] = 100 & gt''Testroom'',''university''">Готовая дипломная работа</a>.'
	gs 'zz_render','','','<b>Основные действия</b>'
	gs 'zz_render','','','<a href="exec:gt''uni_events'',''preparatory_classes''">Подготовительные курсы</a>. Повышают интеллект на 1 единицу за пять занятий.'
	gs 'zz_render','','','<a href="exec:gt''uni_events'',''entrance_exam''">Вступительные экзамены</a>. Расчитываются по формуле интеллект + успеваемость в школе + внешность/10 - опьянение*10'
	gs 'zz_render','','','<a href="exec:gt''uni_events'',''lecture''">Лекции</a>. Тут многое влияет на конечный результ - возбуждение, опъянение, сонливость, настроение.'
	gs 'zz_render','','','<a href="exec:university[''vacation''] = 2 & gt''uni_events'',''exam''">Экзамены - Зимняя сессия 1 курс</a>.'
	gs 'zz_render','','','<a href="exec:university[''vacation''] = 3 & gt''uni_events'',''exam''">Экзамены - Летняя сессия 1 курс</a>.'
	gs 'zz_render','','','<a href="exec:university[''vacation''] = 5 & gt''uni_events'',''exam''">Экзамены - Зимняя сессия 2 курс</a>.'
	gs 'zz_render','','','<a href="exec:university[''vacation''] = 6 & gt''uni_events'',''exam''">Экзамены - Летняя сессия 2 курс</a>.'
	if university['course_work'] >= 100:'<a href="exec:gt''uni_events'',''exam''">Сдать курсовик</a>.'
	if university['graduate_work'] >= 100:'<a href="exec: gt''uni_events'',''exam''">Защитить диплом</a>.'
	gs 'zz_render','','','<b>Локации</b>'
	gs 'zz_render','','','<a href="exec:gt''university'',''start''">Холл универа</a>.'
	gs 'zz_render','','','<a href="exec:gt''university'',''accounting''">Бухгалтерия</a>.'
	gs 'zz_render','','','<a href="exec:gt''university'',''deanery''">Деканат</a>.'
	gs 'zz_render','','','<a href="exec:gt''university'',''toilet''">Туалет</a>. При возбуждении можно мастурбировать в кабинке.'
	gs 'zz_render','','','<a href="exec:university[''student''] = 2 & gt''university'',''library''">Библиотека</a>. Только для студентов.'
	act 'Назад': gt 'Testroom'
end
	!----Качалка в СКК
	gs 'zz_render','','','<a href="exec:GT ''skk_gym_girl'',''shower_GG_random'',1">Душ ивент1.</a>'
	gs 'zz_render','','','<a href="exec:GT ''skk_gym_girl'',''shower_GG_random'',2">Душ ивент2.</a>'
	gs 'zz_render','','','<a href="exec:GT ''skk_gym_girl'',''shower_GG_random'',3">Душ ивент3.</a>'
	gs 'zz_render','','','<a href="exec:GT ''skk_gym_girl'',''shower_GG_random'',4">Душ ивент4.</a>'
	gs 'zz_render','','','<a href="exec:GT ''skk_gym_girl'',''shower_GG_random'',5">Душ ивент5.</a>'
	gs 'zz_render','','','<a href="exec:GT ''skk_gym_girl'',''shower_GG_random'',6">Душ ивент6.</a>'
	gs 'zz_render','','','<a href="exec:GT ''skk_gym_girl'',''random_event''">Душ ивент6.</a>'